# Generated by Django 2.1.5 on 2019-02-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploaderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='topic_images/'),
        ),
    ]
